# Generated by Django 6.0.4 on 2026-04-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='DailyAdvice',
        ),
    ]
