"""Demo posts dataset keyed by topic keywords."""

DEMO_POSTS = {
    'AI': [
        "AI is revolutionizing the way we work and live. So excited about the future!",
        "Artificial intelligence is taking away jobs. This is a major concern for workers.",
        "Machine learning models are getting better every day. The progress is incredible!",
        "I'm worried AI will replace most jobs in the next decade.",
        "AI assistants have made me 3x more productive at work. Highly recommend.",
        "The ethics of AI is something we need to discuss seriously as a society.",
        "ChatGPT helped me write my thesis. AI is an amazing tool for education.",
        "AI bias is a real problem. We need more diverse datasets and researchers.",
        "Just used an AI tool to design my entire website. Mind blown!",
        "AI is just a hype bubble. Most companies can't even use it effectively.",
        "Excited about AI in healthcare. It could save millions of lives.",
        "AI-generated content is flooding the internet with misinformation.",
        "The AI boom is creating amazing opportunities for programmers and entrepreneurs.",
        "I think AI regulation is urgent. We can't let tech companies self-regulate.",
        "AI tutors are helping kids learn at their own pace. Great for education!",
        "Lost my job to automation. Thanks AI. Really appreciate it.",
        "AI is helping scientists discover new drugs faster than ever before.",
        "I'm genuinely scared of superintelligent AI. We need safety research now.",
        "AI art is beautiful and creative. A new form of human expression!",
        "AI writing is soulless and is killing creative industries.",
        "The AI revolution is the biggest economic shift since the Industrial Revolution.",
        "AI hallucinations are a serious problem. Can't trust anything it says.",
        "AI is making programming accessible to everyone. This is democratization!",
        "Tech companies are using AI to spy on us. Privacy is dead.",
        "AI-powered recommendation systems have improved my Netflix experience so much.",
        "AI training consumes insane amounts of energy. Bad for the environment.",
        "AI is helping small businesses compete with big corporations. Love it!",
        "AI deepfakes are getting scary. How will we know what's real?",
        "The open-source AI community is doing incredible work. Future is bright.",
        "AI job screening is biased against minorities. We've proven this repeatedly.",
        "AI is a neutral tool. The ethics depends on how humans use it.",
        "I use AI every day and it's transformed how I approach problem solving.",
        "AI governance needs international cooperation. One country can't do it alone.",
        "AI-powered customer service is actually getting pretty good.",
        "AI is creating more jobs than it's destroying. History shows this with every tech revolution.",
    ],
    'Python': [
        "Python is by far the best programming language for beginners and experts alike!",
        "Python is too slow for production. Use Rust or Go instead.",
        "Just learned Python in 3 months and landed my first dev job! Dreams do come true.",
        "Python's GIL is a fundamental design flaw that limits concurrency.",
        "The Python ecosystem for data science is unbeatable. NumPy, Pandas, scikit-learn!",
        "Python 2 end of life was handled terribly. Still have legacy code nightmares.",
        "Django and FastAPI make building web apps in Python so easy and fun.",
        "Python packaging is a mess. pip, conda, poetry, pipenv — too many choices.",
        "Python is perfect for automation and scripting. Saves me hours every week.",
        "Dynamic typing in Python leads to so many runtime errors. TypeScript for life.",
        "The Python community is incredibly welcoming and helpful. Love this ecosystem.",
        "Python performance is a real bottleneck for our ML inference pipeline.",
        "Jupyter notebooks + Python is the perfect environment for data exploration.",
        "Python syntax is so clean and readable. Other languages feel verbose by comparison.",
        "Python is eating the world — AI, web, automation, it does everything.",
    ],
    'Tech': [
        "Technology is making our lives better in so many ways. Grateful for innovation!",
        "Big tech is monopolizing everything and killing competition.",
        "The smartphone has changed how billions of people communicate and work.",
        "Social media algorithms are designed to be addictive. This is harmful.",
        "Open source technology is the foundation of the modern internet.",
        "Tech layoffs are devastating families across Silicon Valley and beyond.",
        "Cloud computing has democratized access to powerful infrastructure for startups.",
        "Tech companies collect too much personal data. Privacy laws need to catch up.",
        "5G technology is unlocking new possibilities for IoT and smart cities.",
        "The digital divide is leaving billions of people behind. We need tech equity.",
        "Renewable energy tech is advancing faster than anyone predicted. Climate hope!",
        "Cybersecurity threats are growing exponentially. We're not prepared.",
        "VR and AR technology is finally mature enough for mainstream adoption.",
        "Surveillance capitalism is a fundamental threat to democracy.",
        "Blockchain technology has real use cases beyond cryptocurrency speculation.",
        "The metaverse is overhyped vaporware that nobody actually wants.",
        "Tech innovation is the best hope for solving climate change.",
        "E-waste from tech products is an environmental crisis we ignore.",
        "Quantum computing will transform cryptography and drug discovery within a decade.",
        "Tech giants are too powerful and need to be broken up by regulators.",
    ],
    'Finance': [
        "Investing early in index funds is the best financial decision I ever made.",
        "Inflation is destroying people's savings. The economic system is broken.",
        "Compound interest is the eighth wonder of the world. Start investing now!",
        "Credit card debt is a trap designed to keep people financially enslaved.",
        "Financial literacy should be mandatory in schools. Too many people are lost.",
        "The stock market is gambling dressed up in a suit.",
        "Budgeting apps have completely transformed how I manage my money.",
        "Rent prices are out of control. An entire generation is locked out of homeownership.",
        "The FIRE movement (Financial Independence, Retire Early) is genuinely achievable.",
        "Payday loans are predatory products targeting vulnerable people.",
        "Diversification across asset classes is the key to long-term wealth building.",
        "The wealth gap between rich and poor is at historic levels. This is unsustainable.",
        "Automating savings is the single best habit for building wealth.",
        "Student loan debt is destroying the financial future of an entire generation.",
        "Real estate investing has created more millionaires than any other asset class.",
        "Cryptocurrency is a speculative bubble that will eventually collapse.",
        "Having a 6-month emergency fund completely changed my relationship with money.",
        "The banking system benefits the wealthy and exploits the poor.",
        "Robo-advisors and ETFs have democratized investing for ordinary people.",
        "Healthcare costs in the US are the leading cause of personal bankruptcy.",
    ],
    'default': [
        "This is really interesting and worth exploring further.",
        "I have mixed feelings about this topic.",
        "Not sure what to think about this yet.",
        "There are many perspectives to consider here.",
        "This deserves more attention and discussion.",
        "People seem divided on this issue.",
        "The data is unclear and interpretations vary widely.",
        "More research is needed before drawing conclusions.",
        "I see both sides of this debate.",
        "This is more complex than it first appears.",
        "The media coverage has been somewhat one-sided.",
        "Would love to see more nuanced discussion on this topic.",
        "There are legitimate concerns on all sides.",
        "Context matters a lot when evaluating this.",
        "My opinion has evolved as I've learned more.",
    ],
}


def get_demo_posts(topic: str) -> list[str]:
    topic_upper = topic.upper()
    for key in DEMO_POSTS:
        if key.upper() in topic_upper or topic_upper in key.upper():
            posts = DEMO_POSTS[key]
            # Pad to 35+ posts by cycling
            while len(posts) < 35:
                posts = posts + posts
            return posts[:50]
    base = DEMO_POSTS['default']
    while len(base) < 35:
        base = base + base
    return base[:50]
