# Generated by Django 6.0.4 on 2026-04-21 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('negative_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('neutral_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_posts_analyzed', models.IntegerField(default=0)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('top_keywords', models.JSONField(default=list)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sentiment_analyzer.sentimentsearch')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(default='demo', max_length=50)),
                ('sentiment', models.CharField(choices=[('positive', 'Позитивный'), ('negative', 'Негативный'), ('neutral', 'Нейтральный')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('post_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sentiment_analyzer.sentimentresult')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
