# Generated by Django 6.0.4 on 2026-04-28 22:00

import apps.group_collab.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('session_key', models.CharField(max_length=100)),
                ('is_leader', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader'), ('designer', 'Designer'), ('researcher', 'Researcher'), ('speaker', 'Speaker'), ('editor', 'Editor')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('full_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=apps.group_collab.models._gen_code, max_length=8, unique=True)),
                ('max_members', models.PositiveIntegerField(default=4)),
                ('voting_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='group_collab.member')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='group_collab.presentation')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='group_collab.studygroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='group_collab.studygroup'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('group', 'session_key')},
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='group_collab.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='group_collab.studygroup')),
            ],
            options={
                'unique_together': {('group', 'voter_hash')},
            },
        ),
    ]
